config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"
  get "/quotes", to: "quotes#index"
  get "/tolkien", to: "quotes#tolkien"
  get "/tolkien_character/:name", to: "quotes#tolkien_character"
  get "/about", to: "about#index"

  get "/favorites", to: "favorites#index"

  get "/new_quote", to: "new_quote#index"

  


  #routes for filtered routes 

  get "/quotes_list", to: "quotes_list#index"

  get "/quotes_list/bilbo", to: "quotes_list#bilbo"
  
  get "/quotes_list/sauron", to: "quotes_list#sauron"

  get "/quotes_list/gimli", to: "quotes_list#gimli"

  get "/quotes_list/aragorn", to: "quotes_list#aragorn"

  get "/quotes_list/gandalf", to: "quotes_list#gandalf"

  get "/quotes_list/legolas", to: "quotes_list#legolas"

  get "/quotes_list/gollum", to: "quotes_list#gollum"

  get "edit_list", to: "edit_list#editlist"

  


  resources :users

  get "/sign_up", to: "registrations#new"
  post "/sign_up", to: "registrations#create"

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/log_out", to: "sessions#destroy"

  resources :quotes, only: :index do
    member do
      post 'toggle_favorite', to: 'quotes#toggle_favorite'
    end
  end  
end

app/models/quote.rb
class Quote < ApplicationRecord
  def self.random
    Quote.limit(1).order("RANDOM()").first
  end

  validates :quote_content, presence: true
  validates :quote_author, presence: true
  

  acts_as_favoritable
  
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  skip_before_action :verify_authenticity_token
  before_action :set_quote, only: %i[ show edit update destroy ]
  
  # this code needed to get our API helper working and accessible where needed
  require "api_helper"
  include ApiHelper
  
  # GET /quotes or /quotes.json
  def index
    # @quotes = Quote.all
    @weather = weather_api
    @tolkien = tolkien_random_api
    @tolkien_character = tolkien_character_api
  end

  def tolkien
    @tolkien = tolkien_random_api
    render json: @tolkien
  end

  def tolkien_character
    @tolkien_character = tolkien_character_api(params[:name])
    render json: @tolkien_character
  end
  
  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)
  
    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:quote_content, :quote_author, :quote_image)
    end

    #-- Favorites --
    def all_favorites
      @favorite_quotes = User.all_favorites
    end
    
    def toggle_favorite
    
      @quote = Quote.find_by(id: params[:id])
      current_user.favorited?(@quote)  ? current_user.unfavorite(@quote) : current_user.favorite(@quote)
  
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class= "form-tile"> New Quote </p>
  <div>
    <%= form.label :Quote, style: "display: block", class: "subtitle-create" %>
    <%= form.text_field :quote_content, class: "input-quote" %>
  </div>
<br>
  <div>
    <%= form.label :Author, style: "display: block" , class: "subtitle-create" %>
    <%= form.text_field :quote_author, class: "input-quote" %>
  </div>

<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
  
</div>

app/views/quotes/_form2.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class= "form-tile"> Edit Quote </p>
  <div>
    <%= form.label :Quote, style: "display: block", class: "subtitle-create" %>
    <%= form.text_field :quote_content, class: "input-quote" %>
  </div>
<br>
  <div>
    <%= form.label :Author, style: "display: block" , class: "subtitle-create" %>
    <%= form.text_field :quote_author, class: "input-quote" %>
  </div>

<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
  
</div>

app/views/quotes/_like_button.html.erb
<div class="like-icon mx-2 <%= 'yellow' if current_user.favorited?(quote) %>" data-id="<%= quote.id %>">
<%= fa_icon "star" %>
</div>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    "<strong><%= quote.quote_content %></strong>"
  </p>
  <p>
    ..... <%= quote.quote_author %>
  </p>
  <p>
    <%= quote.quote_image %>
  </p>
</div>

app/views/quotes/_toggle_favorite.js.erb
const quoteId = '<%= @quote.id%>'
function toggleLikeButton(quoteId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${quoteId}']`)
  likeButton.classList.toggle('yellow');
}
toggleLikeButton(quoteId);

app/views/quotes/edit.html.erb
<body class="B-body">
<br>
<h1 class= "Edit-quote-title">Editing quote</h1>
  <div class= "edit-links">
    <%= link_to "Show this quote", @quote %> 
    <br>
    <%= link_to "Back to quotes", quotes_path %>
  </div>

<div class="main-ring2">
  <img class="rotate4" src="<%= asset_path('ring5.png') %>" >
    <div class= "create-form2">
      <%= render "form2", quote: @quote, class: "formA" %>
    </div>
</div>
<br>
</body>

app/views/quotes/index.html.erb
<%= javascript_include_tag('clipboard.js') %>
<%= javascript_include_tag('tolkien_api.js') %>
<%= javascript_include_tag('dropdown.js') %>
<%= javascript_include_tag('modal.js') %>

<body class= "main-pages">
  <main class= "main-page">

  <p style="color: green"><%= notice %></p>

  <h1>The Lord of the Quotes</h1>
  <br>
  <h2>What has Middle Earth been saying? </h2>

  <div class="main-ring">
    <div class="container">
    <img id="image" class="rotate2" src="<%= asset_path("ring2.png") %>" >
      <div class="bottom-left"> <b>Great Travel Deal!!!</b><br>
        <%= link_to'https://www.hobbitontours.com/', target: :_blank  do %>
          <p> See Hobbiton!! </p>
        <% end %>
      </div>
      <div class="top-left"> Choose quotes by character:
        <form>
          <select>
            <option disabled hidden selected>Select</option>
            <option value="Aragorn">Aragorn</option>
            <option value="Boromir">Boromir</option>
            <option value="Celeborn">Celeborn</option>
            <option value="Elrond">Elrond</option>
            <option value="Faramir">Faramir</option>
            <option value="Gandalf">Gandalf</option>
          </select>
            <button type="button" class="fetch-specific-quote" style="color:black; background-color:transparent; border: none" >Fetch a Quote!</button>
        </form>
      </div>
      <div class="top-right quoteByAuthor"> 
      <!-- Button trigger modal -->
        <button type="button" id="favoritesModal" class="btn btn-transparent"> <%=fa_icon "star" %> Favourites</button>
          <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Your Favourite Quotes</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Modal end -->
      <div class="bottom-right">Current Weather in<br> <strong>Middle Earth</strong>, Maryland: <br>
        <%= @weather['weather'][0]['description'].titlecase %> <br> <%= @weather['main']['temp'] %> &#8451
        <br>
        <a id="weather" href="https://www.theweathernetwork.com/us/weather/maryland/middle-earth" target="_blank">See details</a>
      </div>
      <div class="centered"> <span id="tolkien" class="quote"> <%= @tolkien['text'] %> ~ <%= @tolkien['character'] %> </span>
      <button class="btn-clipboard" onclick="copyToClipboard()" data-original-title="Copy to clipboard">Copy</button>
        <div class="generate-button-div" > 
        <button class="generate-button" style="color:gold; background-color:transparent; border:none"> Random Quote! </button>
        <a href="#" data-quote-id=<%= @tolkien['id'] %> class="favorite" style="color:gold"><%=fa_icon "star" %> Favorite </a>
        <a href="#" class="unFavorite" style="color:white"> Un Favorite </a>
        </div>
      </div>
    </div> 
  </div>
  <br>
  <!-- Ticker start -->
  <div class="container">
    <div class="ticker">
      <div class="title"><h5>Breaking ME News</h5></div>
        <div class="news">
          <marquee>
            <p>
            Sauron wins Mordor general election with 98.5% of the votes  ///  Hobbit's win Curling Gold Medal at ME Winter Olympics, coach attributes success to "being low to the ground."  ///  Exclusive interview with the Balrog tonight at 9pm, "I'm just misunderstood."  ///  Minas Tirith FC win the Champion's League final 3-2 against Isengard  ///  Rohan Derby mired in controversy after Elvish team, Valaya's Breath, accused of using magic  ///  The Epic Dwarven Brewery Tour will include Khazad-dûm for first time since 2993  ///  Farmers in the Westfold grow a 2708lb pumpkin, beating the famed Farmer Maggot's Guinness Book of ME Records entry of 3025  ///  Goblin factory workers unionize, spokesman releases statement, "Nah dis is fair, innit."  ///  The Nazghul Nine Ballet House announce Middle Earth tour ~ tickets sell out immediately  ///  Weathertop Restoration Fund reaches it's crowdfunding target after mysterious benefactor donates a set of mithril armour  ///  Cave Troll sanctuary in the Misty Mountains set to open summer this year  ///  Final Palantir recovered in a garage sale in Dale, owner say's "We used it as a paperweight for years."  ///  Prancing Pony celebrates its 50th year of operation with a limited run of themed beer steins  ///  Entwives reportedly sighted on the west bank of a southern bow of the river Carnen, flowing into the Sea of Rhûn
            </p>
          </marquee>
        </div>
      </div>
      <br>
    </div>
  </div>
      <!-- Ticker end -->
  <!-- Toast start -->
  <div class="toast" id="toasty" style="position: absolute; top: 50%; right: 50%; transform: translateX(50%);" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header" style="color: #9b620d;">
      <strong class="mr-auto">Copied to clipboard!</strong>
    </div>
    <div class="toast-body"></div>
  </div>
  <!-- Toast end -->
  </main>
</body>

app/views/quotes/new.html.erb
<body class= "B-body">
<br>
<br>  
<h1 class= "create-a-quote">Create a new Quote</h1>
<%= link_to "Quotes", quotes_list_path, class: "see-quotes" %>
<div class="main-ring2">
  <img class="rotate7" src="<%= asset_path('ring5.png') %>" >
    <div class= "create-form">
      <%= render "form", quote: @quote, class: "formA" %>
    </div>
</div>
</div>
<br>
</body>

app/views/quotes/show.html.erb
<body class= "B-body">
<main class="quote-id">

<div class = "show-page">
  <div class="show-quote"
      <%= render @quote %>
  </div>
  <br>
  <div class = "show-icons"> 
  <%= link_to "Edit Quote", edit_quote_path(@quote), class: "edit-icon" %> 
  <%= button_to "Delete Quote ", @quote, class: "btn btn-outline-danger", method: :delete %>
  <%= link_to "Back to Quotes", quotes_list_path, class: "back-icon" %>
  </div>
    </div>
      <p class= "create-notice" ><%= notice %></p>
  </div>

<br>
<br>
<br>
<%= image_tag "walk2.png", class: "walk-pic" %>
</main> 
</body>

app/views/quotes/toggle_favorite.js.erb

function toggleLikeButton(quoteId, favoritedQuote) {
  let likeButton = document.querySelector(`.like-icon[data-id='${quoteId}']`)
  likeButton.classList.toggle('yellow');
  if (likeButton.classList.contains('yellow')) {
    const favoriteList = document.querySelector('.favorites');
    favoriteList.insertAdjacentHTML('beforeend', favoritedCocktail)
  }
  else {
    document.querySelector(`.favorite[data-id='${quoteId}']`).remove()
  }
}
toggleLikeButton(quoteId, '<%= j render "quotes/quote", quote: @quote %>');