config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"
  get "/quotes", to: "quotes#index"
  get "/tolkien", to: "quotes#tolkien"
  get "/tolkien_character/:name", to: "quotes#tolkien_character"
  get "/about", to: "about#index"

  get "/favorites", to: "favorites#index"

  get "/new_quote", to: "new_quote#index"

  


  #routes for filtered routes 

  get "/quotes_list", to: "quotes_list#index"

  get "/quotes_list/bilbo", to: "quotes_list#bilbo"
  
  get "/quotes_list/sauron", to: "quotes_list#sauron"

  get "/quotes_list/gimli", to: "quotes_list#gimli"

  get "/quotes_list/aragorn", to: "quotes_list#aragorn"

  get "/quotes_list/gandalf", to: "quotes_list#gandalf"

  get "/quotes_list/legolas", to: "quotes_list#legolas"

  get "/quotes_list/gollum", to: "quotes_list#gollum"

  get "edit_list", to: "edit_list#editlist"

  


  resources :users

  get "/sign_up", to: "registrations#new"
  post "/sign_up", to: "registrations#create"

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/log_out", to: "sessions#destroy"

  resources :quotes, only: :index do
    member do
      post 'toggle_favorite', to: 'quotes#toggle_favorite'
    end
  end  
end

app/controllers/quotes_list_controller.rb
class QuotesListController< ApplicationController
  def index
    @quotes = Quote.all
    @sauronQuotes = Quote.where(quote_author: "Sauron")
    @bilboQuotes = Quote.where(quote_author: "Bilbo Baggins")
    @aragornQuotes = Quote.where(quote_author: "Aragorn")
    @gandalfQuotes = Quote.where(quote_author: "Gandalf")
    @gimliQuotes = Quote.where(quote_author: "Gimli")
    @legolasQuotes = Quote.where(quote_author: "Legolas")
    @gollumQuotes = Quote.where(quote_author: "Gollum")

  end


def bilbo
  @bilboQuotes = Quote.where(quote_author: "Bilbo Baggins")
end

def sauron 
  @sauronQuotes = Quote.where(quote_author: "Sauron")
end

def gimli 
  @gimliQuotes = Quote.where(quote_author: "Gimli")
end

def gandalf 
  @gandalfQuotes = Quote.where(quote_author: "Gandalf")
end

def aragorn 
  @aragornQuotes = Quote.where(quote_author: "Aragorn")
end

def legolas
  @legolasQuotes = Quote.where(quote_author: "Legolas")
end

def gollum 
  @gollumQuotes = Quote.where(quote_author: "Gollum")
end

end

app/views/quotes_list/aragorn.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Aragorn</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @aragornQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
<div class= "char-portrait"> 
<img id="image" class="aragorn-pic" src="<%= asset_path("aragorn4.png") %>" >
</div>
</main>
</body>

app/views/quotes_list/bilbo.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Bilbo Baggins</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @bilboQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
  <div class= "char-portrait"> 
  <img id="image" class="bilbo-pic" src="<%= asset_path("bilbo4.png") %>" >
  </div>
</main>
</body>

app/views/quotes_list/gandalf.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Gandalf</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @gandalfQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
  <div class= "char-portrait"> 
  <img id="image" class="gandalf-pic" src="<%= asset_path("gandalf5.png") %>" >
  </div>
</main>
</body>

app/views/quotes_list/gimili.html.erb
<body>

<div>

<% @gimiliQuotes.each do |quote,index| %>

  <div id="<%= dom_id quote %>">
  <p>
    <strong>Quote content:</strong>
    <%= quote.quote_content %>
  </p>

  <p>
    <strong>Quote author:</strong>
    <%= quote.quote_author %>
  </p>
 
</div>

 <% end %>


</body>

app/views/quotes_list/gimli.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Gimli</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @gimliQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>

  <div class= "char-portrait"> 
  <img id="image" class="gimli-pic" src="<%= asset_path("gimli5.png") %>" >
  </div>
</main>
</body>

app/views/quotes_list/gollum.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Gollum</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @gollumQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
  <div class= "char-portrait"> 
  <img id="image" class="gandalfp-pic" src="<%= asset_path("gollum2.png") %>" >
</div>
</main>
</body>

app/views/quotes_list/index.html.erb
<body class= "B-body">
  <main class= "B-main">
    <div class="char-list">
    <div class "char-box" class="bilbo">
    <div>
    <%= link_to quotes_list_bilbo_path do %>
      <%= image_tag "bilbo3.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
      <%= link_to "Bilbo Baggins", quotes_list_bilbo_path  %>
      </div>
    </div>
    <div class "char-box" class="aragorn">
    <div>
    <%= link_to quotes_list_aragorn_path do %>
      <%= image_tag "aragorn.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
      <%= link_to "Aragorn", quotes_list_aragorn_path %>
      </div>
    </div>

    <div class "char-box" class= "gandalf">
    <div>
    <%= link_to quotes_list_gandalf_path do %>
      <%= image_tag "gandalf.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
    <%= link_to "Gandalf", quotes_list_gandalf_path %>
    </div>
    </div>  

    <div  class "char-box" class= "sauron">
    <div>
    <%= link_to quotes_list_sauron_path do %>
      <%= image_tag "sauron.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
    <%= link_to "Sauron", quotes_list_sauron_path %>
    </div>
    </div>  

    <div class "char-box" class= "gimli">
    <div>
    <%= link_to quotes_list_gimli_path do %>
      <%= image_tag "gimli.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
    <%= link_to "Gimli", quotes_list_gimli_path %>
    </div>
    </div>  

    <div class "char-box" class= "legolas">
    <div>
    <%= link_to quotes_list_legolas_path do %>
      <%= image_tag "legolas.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
    <%= link_to "Legolas", quotes_list_legolas_path %>
    </div>
    </div>  

    <div class "char-box" class= "gollum">
    <div>
    <%= link_to quotes_list_gollum_path do %>
      <%= image_tag "gollum.png", class: "char-pic" %>
    <% end %>
      </div> 
      <div class="char-name">
    <%= link_to "Gollum", quotes_list_gollum_path %>
    </div>
    </div>  
    </div>
    <br>
    <br>
    <h1 class= "list-title">Whispers of Middle Earth</h1>
    <br>
    <div class="list-quotes">
      <% @quotes.each do |quote,index| %>
        <div id="<%= dom_id quote %>">
      <p>
        <%= quote.quote_content %>
      </p>
      <p>
        <%= quote.quote_author %>
      </p>
      </div>
        <br>
      <% end %>
    <%= link_to "New quote", new_quote_path %>
  </main>
</body>

app/views/quotes_list/legolas.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Legolas</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @legolasQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
<div class= "char-portrait"> 
<img id="image" class= "legolas-pic" src="<%= asset_path("legolas3.png") %>" >
</div>
</main>
</body>

app/views/quotes_list/sauron.html.erb
<body class= "B-body">
<main class= "B-main">
<h1 class="char-name">Sauron</h1>
<div class="char-main"> 
  <div class="char-list-id">
    <% @sauronQuotes.each do |quote,index| %>
      <div id="<%= dom_id quote %>">
        <p><%= quote.quote_content %></p>
      </div>
  <br>
  <br>
<% end %>
<%= link_to "Back", quotes_list_path, class: "back-tick" %>
  </div>
  <div class= "char-portrait"> 
  <img id="image" class="sauron-pic" src="<%= asset_path("sauron2.png") %>" >
</div>
</main>
</body>