config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"
  get "/quotes", to: "quotes#index"
  get "/tolkien", to: "quotes#tolkien"
  get "/tolkien_character/:name", to: "quotes#tolkien_character"
  get "/about", to: "about#index"

  get "/favorites", to: "favorites#index"

  get "/new_quote", to: "new_quote#index"

  


  #routes for filtered routes 

  get "/quotes_list", to: "quotes_list#index"

  get "/quotes_list/bilbo", to: "quotes_list#bilbo"
  
  get "/quotes_list/sauron", to: "quotes_list#sauron"

  get "/quotes_list/gimli", to: "quotes_list#gimli"

  get "/quotes_list/aragorn", to: "quotes_list#aragorn"

  get "/quotes_list/gandalf", to: "quotes_list#gandalf"

  get "/quotes_list/legolas", to: "quotes_list#legolas"

  get "/quotes_list/gollum", to: "quotes_list#gollum"

  get "edit_list", to: "edit_list#editlist"

  


  resources :users

  get "/sign_up", to: "registrations#new"
  post "/sign_up", to: "registrations#create"

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/log_out", to: "sessions#destroy"

  resources :quotes, only: :index do
    member do
      post 'toggle_favorite', to: 'quotes#toggle_favorite'
    end
  end  
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-danger">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_top_nav_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
    
    </div>
  </div>
  
  <section class="navbar-main">
    
    <div class="nav-left">
      <div>
        
        <%= link_to root_path do %>
          <%= fa_icon "home" %> Home
        <% end %>             
      
        <%= link_to [:about] do %>
          <%= fa_icon "id-card" %> About Us
        <% end %>      

        <%= link_to 'https://twitter.com/MiddleE23501801', target: :_blank  do %>
          <%= fa_icon "twitter" %> 
        <% end %>
        
        <%= link_to 'https://www.instagram.com/middleearth013/', target: :_blank  do %>
          <%= fa_icon "instagram" %> 
        <% end %>  
        
        <%= link_to 'https://www.youtube.com/channel/UCkDiXNTFKK72VV267kFbdxA', target: :_blank   do %>
          <%= fa_icon "google" %> 
        <% end %>
      </div>
    </div>

    <div class="nav-admin">
      <% if Current.user && Current.user.admin %>

        <p style="color:red"> <b>Welcome Dark Master</b> </p>
      
        <%= link_to [:new_quote] do %>
          <%= fa_icon "pencil" %> Create Quote
        <% end %>
            
        
        <%= link_to [:edit_list] do %>
          <%=fa_icon "pencil" %> Edit Quotes
          <% end %>
      
      <% end %>   
    </div> 
    
    <div class="user-fav">

      <% if Current.user %>
      <p style="color:green">Logged in as: <b><%= Current.user.name %></b></p>

      <%= link_to [:quotes_list] do %>
        <%= fa_icon "list" %> List Quotes
      <% end %>

    </div> 
          
    <div class="user-log">      
          
      <%= link_to "Sign Out", log_out_path, method: :get %>
      
      <% else %>
        
      <%= link_to "Sign up", sign_up_path %>
      <%= link_to "Sign In", sign_in_path %>
      <% end %>
    </div>  

  </section>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> %>
    <%# <link rel="stylesheet" href="app/assets/css/bootstrap.min.css" media="all"> %>
    <title>LOTQuotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
  </head>
    <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track" => "reload" %> 
    <!-- JavaScript Bundle with Popper --> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> 
    <%= render 'layouts/top_nav_bar' %>
    <%= yield %>
  </body>
</html>